-- AlterTable
ALTER TABLE "data" ADD COLUMN     "hari_meninggal_ayah" TEXT,
ADD COLUMN     "hari_meninggal_ibu" TEXT,
ADD COLUMN     "jenis_kelamin_ayah" TEXT,
ADD COLUMN     "jenis_kelamin_ibu" TEXT,
ADD COLUMN     "meninggal_karena_ayah" TEXT,
ADD COLUMN     "meninggal_karena_ibu" TEXT,
ADD COLUMN     "tanggal_lahir_ayah" TIMESTAMP(3),
ADD COLUMN     "tanggal_lahir_ibu" TIMESTAMP(3),
ADD COLUMN     "tanggal_meninggal_ayah" TIMESTAMP(3),
ADD COLUMN     "tanggal_meninggal_ibu" TIMESTAMP(3),
ADD COLUMN     "tempat_lahir_ayah" TEXT,
ADD COLUMN     "tempat_lahir_ibu" TEXT,
ADD COLUMN     "umur_ayah" TEXT,
ADD COLUMN     "umur_ibu" TEXT;
